config/routes.rb
Rails.application.routes.draw do
  get 'login/new'
  get 'login/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root 'categories#index'
  resources :categories do
    resources :topics do
      resources :comments
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :topics
  mount_uploader :picture, PictureUploader

  accepts_nested_attributes_for :topics
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < ApplicationController

      def index
        @categories = Category.all
        render json: @categories
      end

      def show
        @category = Category.find(params[:id])
        @topics = @category.topics.all
        render json: @topics
      end

    end
  end
end

app/controllers/categories_controller.rb
require 'net/http'
require 'json'


class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    url = 'http://127.0.0.1:8000/posts/posts/'
    uri = URI(url)
    response = Net::HTTP.get(uri)
    @effects = JSON.parse(response)
  end

  def show
    @category = Category.find(params[:id])
    @topics = @category.topics.all
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/index.html.erb
<h1>Category#index</h1>
<p>Find me in app/views/category/index.html.erb</p>
<% @effects.each do |effect| %>
  <div class="col-md-10">
    <%= effect['title'] %></a><br>
    &nbsp
  </div>
<% end %>
<% @categories.each do |category| %>
  <div class="row">
    <div class="col-md-1">
      <% if category.picture_url %>
      <%= image_tag category.picture_url(:thumb) %>
      <% end %>
    </div>
    <div class="col-md-10">
      <a href="<%=  category_path(category.id) %>"><%= category.title %></a><br>
      &nbsp <%= category.description %> <br><br>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1>Category#show</h1>
<p>Find me in app/views/category/show.html.erb</p>
<% @topics.each do |topic| %>
  <a href="<%=  category_topic_path(@category.id, topic.id) %>"><%= topic.title %> <br></a>
  Added by <%= topic.user.email %> <br>
  &nbsp <%= topic.body.truncate(500) %> <br><br>
<% end %>